spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: -
    password: -
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
#create-drop
